//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/_CUSTOM_ASSETS/_EYEAssets/Inputs/PRYCraftInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PRYCraftInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PRYCraftInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PRYCraftInputs"",
    ""maps"": [
        {
            ""name"": ""PRYCraft"",
            ""id"": ""848221f6-8796-47eb-9fd3-3cc03862517e"",
            ""actions"": [
                {
                    ""name"": ""Acceleration"",
                    ""type"": ""Button"",
                    ""id"": ""02f5ff4f-bfce-40b0-aea9-3e35876ea681"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TurnToSide"",
                    ""type"": ""Button"",
                    ""id"": ""e87adf70-fd00-4890-b882-f175ea45a984"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pitch"",
                    ""type"": ""Button"",
                    ""id"": ""164f0969-c020-495d-8e85-cfd433e8630f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Roll"",
                    ""type"": ""Button"",
                    ""id"": ""3264f9b9-010a-457a-ae7b-0315013f47a5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpeedBoost"",
                    ""type"": ""Button"",
                    ""id"": ""5a39cba6-cd3f-4803-b000-b3355347ed8a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""19ece7a6-c493-4ee8-a29b-93481fc73211"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Acceleration"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""8094fc15-8725-4130-a29c-2f27a50c988c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Acceleration"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""24f02690-f3da-4749-af10-26d150150960"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Acceleration"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""XBOX"",
                    ""id"": ""c79a80b3-cafe-4c4b-8432-b5a5eca2eb40"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pitch"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""d90dd203-e928-4aba-ab18-586c71867450"",
                    ""path"": ""<XInputController>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""b789ee4c-d9c7-4086-bdf2-64d7b6dc1f7a"",
                    ""path"": ""<XInputController>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""XBOX"",
                    ""id"": ""5c80dd7e-3749-4f86-a53f-3d6737fb98a6"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Roll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""6085d9ef-4e7c-40b8-9673-5dafc554f55d"",
                    ""path"": ""<XInputController>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""a6b40817-a232-4d55-a379-a1c8e6236936"",
                    ""path"": ""<XInputController>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""XBOX"",
                    ""id"": ""ad9362b8-2034-446b-8c20-f945c6156b30"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TurnToSide"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""93f705fe-87c6-4f69-892d-1f30cb4eca1d"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TurnToSide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""9d3bc3b8-86c0-4785-b700-2e67698faea1"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TurnToSide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e5e2350e-8c53-4d73-93f8-a04f6a0cbb58"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpeedBoost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PRYCraft
        m_PRYCraft = asset.FindActionMap("PRYCraft", throwIfNotFound: true);
        m_PRYCraft_Acceleration = m_PRYCraft.FindAction("Acceleration", throwIfNotFound: true);
        m_PRYCraft_TurnToSide = m_PRYCraft.FindAction("TurnToSide", throwIfNotFound: true);
        m_PRYCraft_Pitch = m_PRYCraft.FindAction("Pitch", throwIfNotFound: true);
        m_PRYCraft_Roll = m_PRYCraft.FindAction("Roll", throwIfNotFound: true);
        m_PRYCraft_SpeedBoost = m_PRYCraft.FindAction("SpeedBoost", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PRYCraft
    private readonly InputActionMap m_PRYCraft;
    private List<IPRYCraftActions> m_PRYCraftActionsCallbackInterfaces = new List<IPRYCraftActions>();
    private readonly InputAction m_PRYCraft_Acceleration;
    private readonly InputAction m_PRYCraft_TurnToSide;
    private readonly InputAction m_PRYCraft_Pitch;
    private readonly InputAction m_PRYCraft_Roll;
    private readonly InputAction m_PRYCraft_SpeedBoost;
    public struct PRYCraftActions
    {
        private @PRYCraftInputs m_Wrapper;
        public PRYCraftActions(@PRYCraftInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Acceleration => m_Wrapper.m_PRYCraft_Acceleration;
        public InputAction @TurnToSide => m_Wrapper.m_PRYCraft_TurnToSide;
        public InputAction @Pitch => m_Wrapper.m_PRYCraft_Pitch;
        public InputAction @Roll => m_Wrapper.m_PRYCraft_Roll;
        public InputAction @SpeedBoost => m_Wrapper.m_PRYCraft_SpeedBoost;
        public InputActionMap Get() { return m_Wrapper.m_PRYCraft; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PRYCraftActions set) { return set.Get(); }
        public void AddCallbacks(IPRYCraftActions instance)
        {
            if (instance == null || m_Wrapper.m_PRYCraftActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PRYCraftActionsCallbackInterfaces.Add(instance);
            @Acceleration.started += instance.OnAcceleration;
            @Acceleration.performed += instance.OnAcceleration;
            @Acceleration.canceled += instance.OnAcceleration;
            @TurnToSide.started += instance.OnTurnToSide;
            @TurnToSide.performed += instance.OnTurnToSide;
            @TurnToSide.canceled += instance.OnTurnToSide;
            @Pitch.started += instance.OnPitch;
            @Pitch.performed += instance.OnPitch;
            @Pitch.canceled += instance.OnPitch;
            @Roll.started += instance.OnRoll;
            @Roll.performed += instance.OnRoll;
            @Roll.canceled += instance.OnRoll;
            @SpeedBoost.started += instance.OnSpeedBoost;
            @SpeedBoost.performed += instance.OnSpeedBoost;
            @SpeedBoost.canceled += instance.OnSpeedBoost;
        }

        private void UnregisterCallbacks(IPRYCraftActions instance)
        {
            @Acceleration.started -= instance.OnAcceleration;
            @Acceleration.performed -= instance.OnAcceleration;
            @Acceleration.canceled -= instance.OnAcceleration;
            @TurnToSide.started -= instance.OnTurnToSide;
            @TurnToSide.performed -= instance.OnTurnToSide;
            @TurnToSide.canceled -= instance.OnTurnToSide;
            @Pitch.started -= instance.OnPitch;
            @Pitch.performed -= instance.OnPitch;
            @Pitch.canceled -= instance.OnPitch;
            @Roll.started -= instance.OnRoll;
            @Roll.performed -= instance.OnRoll;
            @Roll.canceled -= instance.OnRoll;
            @SpeedBoost.started -= instance.OnSpeedBoost;
            @SpeedBoost.performed -= instance.OnSpeedBoost;
            @SpeedBoost.canceled -= instance.OnSpeedBoost;
        }

        public void RemoveCallbacks(IPRYCraftActions instance)
        {
            if (m_Wrapper.m_PRYCraftActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPRYCraftActions instance)
        {
            foreach (var item in m_Wrapper.m_PRYCraftActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PRYCraftActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PRYCraftActions @PRYCraft => new PRYCraftActions(this);
    public interface IPRYCraftActions
    {
        void OnAcceleration(InputAction.CallbackContext context);
        void OnTurnToSide(InputAction.CallbackContext context);
        void OnPitch(InputAction.CallbackContext context);
        void OnRoll(InputAction.CallbackContext context);
        void OnSpeedBoost(InputAction.CallbackContext context);
    }
}
